//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sport_Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class categoria
    {
        public int id_categoria { get; set; }
        public string nombre_categoria { get; set; }
        public int id_articulo { get; set; }
    
        public virtual articulo articulo { get; set; }
    }
}
