//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sport_Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_factura
    {
        public int id_factura { get; set; }
        public int id_carrito_de_compra { get; set; }
        public int num_factura { get; set; }
        public decimal cantidad { get; set; }
        public decimal precio { get; set; }
    
        public virtual carrito_de_compra carrito_de_compra { get; set; }
        public virtual factura factura { get; set; }
    }
}
