//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sport_Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class ubicacion
    {
        public int id_cliente { get; set; }
        public int id_direccion { get; set; }
        public int id_empleado { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual direccion direccion { get; set; }
        public virtual empleado empleado { get; set; }
    }
}
